name: Release

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  release:
    name: Prepare release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Build
      - name: Build the file
        run: |
          cd /home/runner/work/ha-wall-clock-card/ha-wall-clock-card
          yarn install
          npm run build

      # Upload build file to the release as an asset.
      - name: Upload asset to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /home/runner/work/ha-wall-clock-card/ha-wall-clock-card/dist/wall-clock-card.js
          asset_name: wall-clock-card.js
          tag: ${{ github.ref }}
          overwrite: true
